### ISSUE TITLE
Refused to set unsafe header "user-agent"

### ISSUE THREAD

**Issue by markhats** [ndaidong/oembed-parser#128]
Hi

I'm getting the following console error when using this lib in Chrome.

<img width="944" alt="image" src="https://user-images.githubusercontent.com/3472245/155293612-a47b32e8-324b-43a0-86a3-c60d4637f529.png">

Any ideas how to prevent this?

Thanks.

**Comment by ndaidong** [comment]
@markhats thank you, it seems relate to Chrome secure policy.

**Comment by HardikPanchal427345** [comment]
JUST REMOVE THE USER AGENT HEADER..

**Comment by dJani97** [comment]
@ndaidong 

I've tried doing the following before calling `extract(url)`:

```typescript
setRequestOptions({
  headers: {
    accept: 'application/json; charset=utf-8',
  },
});
```
and
```typescript
setRequestOptions({
  headers: {
    'user-agent': '',
    accept: 'application/json; charset=utf-8',
  },
});
```
and
```typescript
setRequestOptions({
  headers: {
    'user-agent': undefined,
    accept: 'application/json; charset=utf-8',
  },
});
```
and
```typescript
setRequestOptions({
  headers: {
    'user-agent': null,
    accept: 'application/json; charset=utf-8',
  },
});
```

None of these helped, I'm still getting `Refused to set unsafe header "user-agent"` on the console.

I couldn't try the `extract(String url, Object params, Object fetchOptions)` option, because in `index.d.ts` this method is listed with 2 parameters only.

Can you help me out on how to avoid this errror?

**Comment by ndaidong** [comment]
@dJani97 thank you for raising issue. If you are using TypeScript , there is exactly some mistakes in type declaration. I will release v3.1.3 to fix. Please test it again after that.
