### ISSUE TITLE
Make node-fetch optional for use in browser

### ISSUE THREAD

**Issue by Ghostfly** [ndaidong/oembed-parser#41]
Hi ! Great library but only for node ? :( 

Problem :
Needed an oembed-parser for a website (who grab through a proxy), but can't use that lib due to "node-fetch" required.. (and global.Promise patch)

Proposal : 

Is there any way to add a proxy and a node param in extract options, that way we can make that lib available in the browser in minutes !

(made changes in this fork : https://github.com/ghostfly/oembed-parser)

Proxy used : Cors anywhere

Thanks for the work :)

**Comment by ndaidong** [comment]
Thank you for your idea. It's time to refactor this lib with more flexible approach.

**Comment by ndaidong** [comment]
@Ghostfly theoretically we can make oembed-parser work at the brower side easily, just call native browsers Fetch APIs instead of node-fetch. Browsers' Fetch APIs supports [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) as default. 

But nowadays some vendors created a new concept called [CORB - Cross-Origin Read Blocking](https://www.chromestatus.com/feature/5629709824032768). In the browsers those have this feature, we can still fetch (cross domain) successfully, but the response is alway empty. I've tested on several browsers, it seems only Firefox didn't implemented CORB. Latest versions of Chrome, Chrominum, Opera, Vivaldi did. 

So we stop planing to bring oembed-parser to client side, until there is a better approach.

**Comment by Ghostfly** [comment]
Hum, seems that i'm not impacted since i request on the same domain.. 

Thanks for trying, will keep my fork updated, np 👍
